jobs:
  include:
    - stage: "Test"
      name: "Build font"
      language: node_js
      node_js: 8
      script:
        - npm run build

    - stage: deploy
      name: "NPM Package"
      language: node_js
      node_js: 8
      if: branch = master

      deploy:
        provider: npm
        email: "johanringmann@gmail.com"
        api_key: "$NPM_KEY"
        on:
          branch: master

notifications:
  email:
    on_success: never
    on_failure: change
